name: test_env

services:
  computer_env:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcpworld:pc-canary
    container_name: mcpworld
    volumes:
      - ../../MCPWorld/:/workspace
    shm_size: "1g"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - "5900:5900"
      - "5904:5904"
      - "8501:8501"
      - "6080:6080"
      # - "8080:8080"
    environment:
      - ANTHROPIC_API_KEY=dummy_api_key
      # - OPENAI_BASE_URL=http://localhost:11434
      - OPENAI_BASE_URL=http://host.docker.internal:11434
      - OPENAI_ENDPOINT=/v1/chat/completions
      - OPENAI_TIMEOUT=1000
      - WIDTH=1000
      - HEIGHT=1000
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - testbed-docker
    command: /bin/bash /workspace/docker/start_service.sh
    tty: true
    stdin_open: true

  ollama:
    volumes:
      - ../ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - testbed-docker
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]


networks:
  testbed-docker:
    external: false
